tabela = ('Palmeiras','São Paulo','Corinthians','Bahia','Fluminense','Athletico-PR','Bragantino','Grêmio','Chapecoense','Mirassol','Flamengo','Coritiba','Santos','Botafogo','EC Vitória,Remo','Atlético-MG','Internacional', 'Cruzeiro', 'Vasco da Gama')
print(f'Times do brasileirão: {tabela}')
print('-='*20)
print(f'Os 5 primeiros são: {tabela[0:6]}')
print('-='*20)
print(f'Os 4 ultimos são: {tabela[15:]}')
print('-='*20)
print(f'Em ordem alfabetica: {sorted(tabela)}')
print('-='*15)
print(f'O grêmio está na {tabela.index("Grêmio")+1} posição')
print('-='*15)
