n = input('Digite algo: ')
print(f'Tipo primitivo: {type(n)}')
print(f'É um numero? {n.isnumeric()}')
print(f'Contém apenas espaços? {n.isspace()}')
print(f'É alfabetico? {n.isalpha()}')
print('Está em apenas Maiusculo? ', n.isupper())
print('Está em apenas minusculo? ', n.islower())
print('É alfanumerico? ', n.isalnum())
print('Está capitalizado? ',n.istitle())